"""
BIS Standards Catalog Adapter for Automated Acquisition.
Discovers and extracts standards across 7 official BIS domains with strict taxonomy validation.
"""

import logging
from typing import Any, Dict, List, Optional

from ai.acquisition.crawler_models import DiscoveredStandard, DiscoveryDocumentType, normalize_standard_number
from ai.acquisition.sources.base import BaseSourceAdapter
from ai.taxonomy.validator import get_taxonomy_validator

logger = logging.getLogger(__name__)

# Authoritative BIS Standards Catalog Definitions
BIS_STANDARDS_CATALOG: List[Dict[str, Any]] = [
    # 1. Electrical Domain (ETD Committees)
    {
        "standard_number": "IS 374 : 2019",
        "title": "Electric Ceiling Fans — Specification (Fourth Revision)",
        "edition": "Fourth Revision",
        "document_type": "standard",
        "domain": "electrical",
        "category": "fans",
        "product_type": "electric_ceiling_fans",
        "pub_date": "2019-07-01",
        "valid_from": "2019-07-01",
        "valid_until": "2026-07-31",
        "source_url": "https://standardsbis.bsbedge.com/is374_2019",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is374_2019.pdf",
        "authority": "Bureau of Indian Standards (ETD 05)",
        "content_summary": "Covers air delivery (≥210 m³/min for 1200 mm), power input (≤50 W), service value (≥4.2 m³/min/W), and insulation resistance for ceiling fans.",
    },
    {
        "standard_number": "IS 374 : 2026",
        "title": "Electric Ceiling Fans — Specification (Fifth Revision - Energy Efficient BLDC)",
        "edition": "Fifth Revision",
        "document_type": "standard",
        "domain": "electrical",
        "category": "fans",
        "product_type": "electric_ceiling_fans",
        "pub_date": "2026-08-01",
        "valid_from": "2026-08-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is374_2026",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is374_2026.pdf",
        "authority": "Bureau of Indian Standards (ETD 05)",
        "content_summary": "Fifth revision introducing mandatory BLDC motor efficiency (≥220 m³/min air delivery at ≤35 W power input) and electronic speed regulators.",
    },
    {
        "standard_number": "IS 555 : 1979",
        "title": "Specification for Table Type Electric Fans and Regulators (Second Revision)",
        "edition": "Second Revision",
        "document_type": "standard",
        "domain": "electrical",
        "category": "fans",
        "product_type": "electric_table_fans",
        "pub_date": "1979-11-01",
        "valid_from": "1979-11-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is555_1979",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is555_1979.pdf",
        "authority": "Bureau of Indian Standards (ETD 05)",
        "content_summary": "Specifies minimum air delivery of 70 m³/min for 400 mm table fans and max 55 W power input.",
    },
    {
        "standard_number": "IS 2312 : 1967",
        "title": "Specification for Propeller Type AC Ventilating and Exhaust Fans (First Revision)",
        "edition": "First Revision",
        "document_type": "standard",
        "domain": "electrical",
        "category": "fans",
        "product_type": "exhaust_fans",
        "pub_date": "1967-06-01",
        "valid_from": "1967-06-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is2312_1967",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is2312_1967.pdf",
        "authority": "Bureau of Indian Standards (ETD 05)",
        "content_summary": "Covers commercial and domestic exhaust fans, impeller balance, sound levels, and minimum air delivery.",
    },
    {
        "standard_number": "IS 302 (Part 1) : 2024",
        "title": "Safety of Household and Similar Electrical Appliances — Part 1: General Requirements (Second Revision)",
        "edition": "Second Revision",
        "document_type": "standard",
        "domain": "electrical",
        "category": "household_appliances",
        "product_type": "safety_of_household_appliances",
        "pub_date": "2024-03-01",
        "valid_from": "2024-03-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is302_1_2024",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is302_1_2024.pdf",
        "authority": "Bureau of Indian Standards (ETD 32)",
        "content_summary": "General electrical safety, leakage current limits (≤0.75 mA for Class I), electric strength test (1250 V AC), and creepage distance.",
    },
    {
        "standard_number": "IS 366 : 1991",
        "title": "Electric Irons — Specification (Third Revision)",
        "edition": "Third Revision",
        "document_type": "standard",
        "domain": "electrical",
        "category": "household_appliances",
        "product_type": "electric_irons",
        "pub_date": "1991-08-01",
        "valid_from": "1991-08-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is366_1991",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is366_1991.pdf",
        "authority": "Bureau of Indian Standards (ETD 32)",
        "content_summary": "Soleplate temperature control, drop test from 1 m without breakage, thermostat endurance 50 000 cycles, and steaming rate for steam irons.",
    },
    {
        "standard_number": "IS 2082 : 2018",
        "title": "Stationary Storage Type Electric Water Heaters (Fifth Revision)",
        "edition": "Fifth Revision",
        "document_type": "standard",
        "domain": "electrical",
        "category": "household_appliances",
        "product_type": "storage_water_heaters",
        "pub_date": "2018-05-01",
        "valid_from": "2018-05-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is2082_2018",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is2082_2018.pdf",
        "authority": "Bureau of Indian Standards (ETD 32)",
        "content_summary": "Standing loss limits, hydraulic proof pressure of tank (≥ 1.0 MPa), thermostat cut-off at 95°C, and energy efficiency rating.",
    },
    {
        "standard_number": "IS 368 : 2014",
        "title": "Electric Immersion Water Heaters — Specification (Fifth Revision)",
        "edition": "Fifth Revision",
        "document_type": "standard",
        "domain": "electrical",
        "category": "household_appliances",
        "product_type": "electric_immersion_heaters",
        "pub_date": "2014-04-01",
        "valid_from": "2014-04-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is368_2014",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is368_2014.pdf",
        "authority": "Bureau of Indian Standards (ETD 32)",
        "content_summary": "Tubular sheathed heating elements, minimum water depth marking, earthing continuity, and high voltage test at 1500 V AC.",
    },
    {
        "standard_number": "IS 694 : 2010",
        "title": "Polyvinyl Chloride Insulated Cables for Working Voltages up to and Including 1100 V (Fourth Revision)",
        "edition": "Fourth Revision",
        "document_type": "standard",
        "domain": "electrical",
        "category": "cables_conductors",
        "product_type": "pvc_insulated_cables",
        "pub_date": "2010-06-01",
        "valid_from": "2010-06-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is694_2010",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is694_2010.pdf",
        "authority": "Bureau of Indian Standards (ETD 09)",
        "content_summary": "Maximum conductor resistance at 20°C (12.1 Ω/km for 1.5 sq mm) and 3 kV AC water immersion test.",
    },
    {
        "standard_number": "IS 7098 (Part 1) : 1988",
        "title": "Cross-Linked Polyethylene Insulated Thermoplastic Sheathed Cables — Part 1: Working Voltages up to 1100 V",
        "edition": "First Revision",
        "document_type": "standard",
        "domain": "electrical",
        "category": "cables_conductors",
        "product_type": "cross_linked_polyethylene_cables",
        "pub_date": "1988-12-01",
        "valid_from": "1988-12-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is7098_1_1988",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is7098_1_1988.pdf",
        "authority": "Bureau of Indian Standards (ETD 09)",
        "content_summary": "XLPE insulation for power distribution, max conductor operating temp 90°C, hot set elongation ≤ 175%, and spark testing at 11 kV AC.",
    },
    {
        "standard_number": "IS 398 (Part 2) : 1996",
        "title": "Aluminium Conductors for Overhead Transmission Purposes — Part 2: Aluminium Conductors, Galvanized Steel-Reinforced (ACSR)",
        "edition": "Third Revision",
        "document_type": "standard",
        "domain": "electrical",
        "category": "cables_conductors",
        "product_type": "conductors_for_overhead_lines",
        "pub_date": "1996-03-01",
        "valid_from": "1996-03-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is398_2_1996",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is398_2_1996.pdf",
        "authority": "Bureau of Indian Standards (ETD 09)",
        "content_summary": "Tensile strength of steel core, zinc coating mass on galvanized wires, resistance of EC grade aluminium wires, and lay ratio.",
    },
    {
        "standard_number": "IS 3854 : 1997",
        "title": "Switches for Domestic and Similar Fixed Electrical Installations (Second Revision)",
        "edition": "Second Revision",
        "document_type": "standard",
        "domain": "electrical",
        "category": "switches_accessories",
        "product_type": "switches_for_domestic_use",
        "pub_date": "1997-08-01",
        "valid_from": "1997-08-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is3854_1997",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is3854_1997.pdf",
        "authority": "Bureau of Indian Standards (ETD 14)",
        "content_summary": "Making and breaking capacity, temperature rise ≤ 45 K on terminals, endurance test 40 000 operations at rated current and voltage.",
    },
    {
        "standard_number": "IS 1293 : 2019",
        "title": "Plugs and Socket-Outlets for Domestic and Similar Purposes of Rated Voltage up to 250 V (Fourth Revision)",
        "edition": "Fourth Revision",
        "document_type": "standard",
        "domain": "electrical",
        "category": "switches_accessories",
        "product_type": "plugs_and_socket_outlets",
        "pub_date": "2019-11-01",
        "valid_from": "2019-11-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is1293_2019",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is1293_2019.pdf",
        "authority": "Bureau of Indian Standards (ETD 14)",
        "content_summary": "6 A and 16 A 3-pin configuration, shutter mechanism on live sockets, terminal pull force, and dielectric strength test at 2000 V AC.",
    },
    {
        "standard_number": "IS 1653 : 1972",
        "title": "Specification for Rigid Steel Conduits for Electrical Wiring (Second Revision)",
        "edition": "Second Revision",
        "document_type": "standard",
        "domain": "electrical",
        "category": "switches_accessories",
        "product_type": "conduits_for_electrical_installations",
        "pub_date": "1972-04-01",
        "valid_from": "1972-04-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is1653_1972",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is1653_1972.pdf",
        "authority": "Bureau of Indian Standards (ETD 14)",
        "content_summary": "Dimension tolerances, threaded couplings, bending test without cracking of seam or enamel coating, and electrical continuity.",
    },
    {
        "standard_number": "IS 12640 (Part 1) : 2016",
        "title": "Residual Current Operated Circuit-Breakers for Household and Similar Uses (RCCBs) - Part 1",
        "edition": "First Edition",
        "document_type": "standard",
        "domain": "electrical",
        "category": "switches_accessories",
        "product_type": "switches_for_domestic_use",
        "pub_date": "2016-09-01",
        "valid_from": "2016-09-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is12640_1_2016",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is12640_1_2016.pdf",
        "authority": "Bureau of Indian Standards (ETD 07)",
        "content_summary": "Tripping time characteristics for 30 mA personal protection RCCBs, rated short-circuit capacity, and dielectric strength.",
    },

    # 2. Electronics & IT Domain (LITD Committees)
    {
        "standard_number": "IS 16102 (Part 1) : 2012",
        "title": "Self-Ballasted LED Lamps for General Lighting Services — Part 1: Safety Requirements",
        "edition": "First Edition",
        "document_type": "standard",
        "domain": "electronics_it",
        "category": "lighting_systems",
        "product_type": "self_ballasted_led_lamps",
        "pub_date": "2012-05-01",
        "valid_from": "2012-05-01",
        "valid_until": "2026-08-29",
        "source_url": "https://standardsbis.bsbedge.com/is16102_1_2012",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is16102_1_2012.pdf",
        "authority": "Bureau of Indian Standards (LITD 23)",
        "content_summary": "Specifies 4 MΩ insulation resistance at 500 V DC, mechanical cap torque (3.0 Nm B22d, 1.2 Nm E17), and temperature rise.",
    },
    {
        "standard_number": "IS 16102 (Part 1) : 2026",
        "title": "Self-Ballasted LED Lamps for General Lighting Services — Part 1: Safety Requirements (First Revision)",
        "edition": "First Revision",
        "document_type": "standard",
        "domain": "electronics_it",
        "category": "lighting_systems",
        "product_type": "self_ballasted_led_lamps_r1",
        "pub_date": "2026-08-01",
        "valid_from": "2026-08-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is16102_1_2026",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is16102_1_2026.pdf",
        "authority": "Bureau of Indian Standards (LITD 23)",
        "content_summary": "Revised standard with 48 h / 91-95% RH humidity treatment, 4 MΩ at 500 V DC, 4000 V AC electric strength, and 3.0 Nm mandatory torque for GX53 caps.",
    },
    {
        "standard_number": "IS 616 : 2017",
        "title": "Audio, Video and Similar Electronic Apparatus — Safety Requirements (Fourth Revision)",
        "edition": "Fourth Revision",
        "document_type": "standard",
        "domain": "electronics_it",
        "category": "audio_video",
        "product_type": "audio_video_apparatus",
        "pub_date": "2017-06-01",
        "valid_from": "2017-06-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is616_2017",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is616_2017.pdf",
        "authority": "Bureau of Indian Standards (LITD 07)",
        "content_summary": "Electric shock hazards, dielectric strength (2 kV AC), enclosure impact testing (0.5 J), and temperature rise.",
    },
    {
        "standard_number": "IS 13252 (Part 1) : 2010",
        "title": "Information Technology Equipment — Safety — Part 1: General Requirements (Second Revision)",
        "edition": "Second Revision",
        "document_type": "standard",
        "domain": "electronics_it",
        "category": "it_equipment",
        "product_type": "it_equipment_safety",
        "pub_date": "2010-09-01",
        "valid_from": "2010-09-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is13252_1_2010",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is13252_1_2010.pdf",
        "authority": "Bureau of Indian Standards (LITD 07)",
        "content_summary": "Electrical safety, touch current limits (≤0.25 mA for Class II), and power supply insulation.",
    },
    {
        "standard_number": "IS 16046 (Part 2) : 2018",
        "title": "Secondary Cells and Batteries for Portable Applications — Part 2: Lithium Systems",
        "edition": "First Edition",
        "document_type": "standard",
        "domain": "electronics_it",
        "category": "batteries_cells",
        "product_type": "secondary_lithium_batteries",
        "pub_date": "2018-08-01",
        "valid_from": "2018-08-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is16046_2_2018",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is16046_2_2018.pdf",
        "authority": "Bureau of Indian Standards (LITD 10)",
        "content_summary": "Continuous charging at constant voltage, external short circuit at 55°C, free fall test from 1.0 m, and thermal abuse test at 130°C.",
    },
    {
        "standard_number": "IS 16444 (Part 1) : 2015",
        "title": "AC Static Direct Connected kWh Smart Meters — Part 1: Electricity Metering",
        "edition": "First Edition",
        "document_type": "standard",
        "domain": "electronics_it",
        "category": "smart_meters",
        "product_type": "ac_static_smart_meters",
        "pub_date": "2015-08-01",
        "valid_from": "2015-08-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is16444_1_2015",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is16444_1_2015.pdf",
        "authority": "Bureau of Indian Standards (LITD 10)",
        "content_summary": "Accuracy Class 1.0 and 2.0, two-way communication protocol compliance, tamper detection, and load limit disconnection.",
    },
    {
        "standard_number": "IS 15885 (Part 1) : 2011",
        "title": "Lamp Controlgear — Part 1: General and Safety Requirements",
        "edition": "First Edition",
        "document_type": "standard",
        "domain": "electronics_it",
        "category": "lighting_systems",
        "product_type": "lamp_controlgear",
        "pub_date": "2011-04-01",
        "valid_from": "2011-04-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is15885_1_2011",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is15885_1_2011.pdf",
        "authority": "Bureau of Indian Standards (LITD 23)",
        "content_summary": "Creepage distances, insulation resistance, thermal endurance, fault condition testing, and protection against accidental contact.",
    },
    {
        "standard_number": "IS 16101 : 2012",
        "title": "General Lighting — LEDs and LED Modules — Terms and Definitions",
        "edition": "First Edition",
        "document_type": "standard",
        "domain": "electronics_it",
        "category": "lighting_systems",
        "product_type": "led_terms_definitions",
        "pub_date": "2012-05-01",
        "valid_from": "2012-05-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is16101_2012",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is16101_2012.pdf",
        "authority": "Bureau of Indian Standards (LITD 23)",
        "content_summary": "Standardized vocabulary and normative terminology for light emitting diodes, phosphor conversion, modules, and luminous efficacy.",
    },
    {
        "standard_number": "IS 16103 (Part 1) : 2012",
        "title": "LED Modules for General Lighting — Part 1: Safety Requirements",
        "edition": "First Edition",
        "document_type": "standard",
        "domain": "electronics_it",
        "category": "lighting_systems",
        "product_type": "led_modules",
        "pub_date": "2012-05-01",
        "valid_from": "2012-05-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is16103_1_2012",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is16103_1_2012.pdf",
        "authority": "Bureau of Indian Standards (LITD 23)",
        "content_summary": "Classification of integral and built-in modules, electric strength test, screwless terminal reliability, and thermal management safety.",
    },
    {
        "standard_number": "IS 16107 (Part 2/Sec 1) : 2012",
        "title": "Luminaires Performance — Part 2: Particular Requirements, Section 1: LED Luminaires",
        "edition": "First Edition",
        "document_type": "standard",
        "domain": "electronics_it",
        "category": "lighting_systems",
        "product_type": "led_luminaires",
        "pub_date": "2012-05-01",
        "valid_from": "2012-05-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is16107_2_1_2012",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is16107_2_1_2012.pdf",
        "authority": "Bureau of Indian Standards (LITD 23)",
        "content_summary": "Luminous flux maintenance (L70 at 25 000 hours), correlated colour temperature (CCT) tolerance, and initial efficacy limits.",
    },
    {
        "standard_number": "IS 16242 (Part 1) : 2014",
        "title": "Uninterruptible Power Systems (UPS) — Part 1: General and Safety Requirements for UPS",
        "edition": "First Edition",
        "document_type": "standard",
        "domain": "electronics_it",
        "category": "power_supplies",
        "product_type": "uninterruptible_power_systems",
        "pub_date": "2014-06-01",
        "valid_from": "2014-06-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is16242_1_2014",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is16242_1_2014.pdf",
        "authority": "Bureau of Indian Standards (LITD 10)",
        "content_summary": "Operator safety in operator access areas, emergency switching device, battery enclosure ventilation, and temperature limits.",
    },
    {
        "standard_number": "IS 16333 (Part 3) : 2022",
        "title": "Mobile Phone Handsets — Part 3: Language Support for Indian Languages (Third Revision)",
        "edition": "Third Revision",
        "document_type": "standard",
        "domain": "electronics_it",
        "category": "telecom_mobile",
        "product_type": "mobile_handsets_indian_languages",
        "pub_date": "2022-06-01",
        "valid_from": "2022-06-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is16333_3_2022",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is16333_3_2022.pdf",
        "authority": "Bureau of Indian Standards (LITD 13)",
        "content_summary": "Mandatory readability and text input for 22 scheduled Indian official languages, keypad layout, and font rendering verification.",
    },
    {
        "standard_number": "IS 16500 : 2017",
        "title": "CCTV Surveillance Systems for Use in Security Applications — Video Systems",
        "edition": "First Edition",
        "document_type": "standard",
        "domain": "electronics_it",
        "category": "surveillance_systems",
        "product_type": "cctv_cameras",
        "pub_date": "2017-09-01",
        "valid_from": "2017-09-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is16500_2017",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is16500_2017.pdf",
        "authority": "Bureau of Indian Standards (LITD 15)",
        "content_summary": "Video resolution (≥1080p for Full HD), dynamic range, frame rate stability (≥25 fps), low light sensitivity, and cybersecurity conformance.",
    },
    {
        "standard_number": "IS 18112 : 2022",
        "title": "Television Sets — Integrated Digital Terrestrial Television Receivers — Specification",
        "edition": "First Edition",
        "document_type": "standard",
        "domain": "electronics_it",
        "category": "audio_video",
        "product_type": "digital_television_receivers",
        "pub_date": "2022-04-01",
        "valid_from": "2022-04-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is18112_2022",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is18112_2022.pdf",
        "authority": "Bureau of Indian Standards (LITD 07)",
        "content_summary": "DVB-T2 tuner built-in receiver requirement, RF sensitivity, video decoding (H.264/HEVC), and multi-channel audio format support.",
    },
    {
        "standard_number": "IS 7354 : 1974",
        "title": "Specification for Hearing Aids (First Edition)",
        "edition": "First Edition",
        "document_type": "standard",
        "domain": "electronics_it",
        "category": "assistive_devices",
        "product_type": "hearing_aids",
        "pub_date": "1974-03-01",
        "valid_from": "1974-03-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is7354_1974",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is7354_1974.pdf",
        "authority": "Bureau of Indian Standards (LITD 07)",
        "content_summary": "Acoustic gain, maximum acoustic output sound pressure level (OSPL90), harmonic distortion, and frequency response curve.",
    },

    # 3. Construction & Civil Domain (CED Committees)
    {
        "standard_number": "IS 269 : 2015",
        "title": "Ordinary Portland Cement — Specification (Sixth Revision)",
        "edition": "Sixth Revision",
        "document_type": "standard",
        "domain": "construction_civil",
        "category": "cement",
        "product_type": "ordinary_portland_cement",
        "pub_date": "2015-11-01",
        "valid_from": "2015-11-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is269_2015",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is269_2015.pdf",
        "authority": "Bureau of Indian Standards (CED 02)",
        "content_summary": "Specifies 33, 43, and 53 grade OPC. 53 Grade requires 27 MPa (3 days), 37 MPa (7 days), 53 MPa (28 days). Initial setting time ≥ 30 min.",
    },
    {
        "standard_number": "IS 1489 (Part 1) : 2015",
        "title": "Portland Pozzolana Cement — Specification — Part 1: Fly Ash Based (Third Revision)",
        "edition": "Third Revision",
        "document_type": "standard",
        "domain": "construction_civil",
        "category": "cement",
        "product_type": "portland_pozzolana_cement",
        "pub_date": "2015-11-01",
        "valid_from": "2015-11-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is1489_1_2015",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is1489_1_2015.pdf",
        "authority": "Bureau of Indian Standards (CED 02)",
        "content_summary": "PPC fly ash constituent limits 15% to 35% by mass, compressive strength 16 MPa (3 days), 22 MPa (7 days), 33 MPa (28 days).",
    },
    {
        "standard_number": "IS 455 : 2015",
        "title": "Portland Slag Cement — Specification (Sixth Revision)",
        "edition": "Sixth Revision",
        "document_type": "standard",
        "domain": "construction_civil",
        "category": "cement",
        "product_type": "portland_slag_cement",
        "pub_date": "2015-11-01",
        "valid_from": "2015-11-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is455_2015",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is455_2015.pdf",
        "authority": "Bureau of Indian Standards (CED 02)",
        "content_summary": "Granulated blast furnace slag content 25% to 70% by mass, sound resistance, sulfate resistance, and setting time requirements.",
    },
    {
        "standard_number": "IS 1786 : 2008",
        "title": "High Strength Deformed Steel Bars and Wires for Concrete Reinforcement — Specification (Fourth Revision)",
        "edition": "Fourth Revision",
        "document_type": "standard",
        "domain": "construction_civil",
        "category": "steel_metals",
        "product_type": "high_strength_deformed_steel_bars_2008",
        "pub_date": "2008-01-01",
        "valid_from": "2008-01-01",
        "valid_until": "2024-01-01",
        "source_url": "https://standardsbis.bsbedge.com/is1786_2008",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is1786_2008.pdf",
        "authority": "Bureau of Indian Standards (CED 54)",
        "content_summary": "Fe 415 (yield ≥415 MPa, elong ≥14.5%), Fe 500 (yield ≥500 MPa, elong ≥12.0%), Fe 550 (yield ≥550 MPa, elong ≥10.0%).",
    },
    {
        "standard_number": "IS 1786 : 2024",
        "title": "High Strength Deformed Steel Bars and Wires for Concrete Reinforcement — Specification (Fifth Revision)",
        "edition": "Fifth Revision",
        "document_type": "standard",
        "domain": "construction_civil",
        "category": "steel_metals",
        "product_type": "high_strength_deformed_steel_bars",
        "pub_date": "2024-07-01",
        "valid_from": "2024-07-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is1786_2024",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is1786_2024.pdf",
        "authority": "Bureau of Indian Standards (CED 54)",
        "content_summary": "Fe 500D (yield ≥500 MPa, elong ≥16.0%, TS/YS ≥1.10), Fe 550D, and new Fe 650 grade.",
    },
    {
        "standard_number": "IS 2062 : 2011",
        "title": "Hot Rolled Medium and High Tensile Structural Steel — Specification (Seventh Revision)",
        "edition": "Seventh Revision",
        "document_type": "standard",
        "domain": "construction_civil",
        "category": "steel_metals",
        "product_type": "structural_steel_standard_quality",
        "pub_date": "2011-06-01",
        "valid_from": "2011-06-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is2062_2011",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is2062_2011.pdf",
        "authority": "Bureau of Indian Standards (CED 54)",
        "content_summary": "Structural steel designations E250, E300, E350, E410, E450, impact test sub-qualities (BR, B0, C), and chemical composition limits.",
    },
    {
        "standard_number": "IS 383 : 2016",
        "title": "Coarse and Fine Aggregate for Concrete — Specification (Third Revision)",
        "edition": "Third Revision",
        "document_type": "standard",
        "domain": "construction_civil",
        "category": "concrete_aggregates",
        "product_type": "coarse_and_fine_aggregates",
        "pub_date": "2016-01-01",
        "valid_from": "2016-01-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is383_2016",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is383_2016.pdf",
        "authority": "Bureau of Indian Standards (CED 02)",
        "content_summary": "Grading limits for coarse aggregate, Zone I to IV fine aggregates, manufactured sand, recycled concrete aggregate (RCA), and soundness tests.",
    },
    {
        "standard_number": "IS 456 : 2000",
        "title": "Plain and Reinforced Concrete — Code of Practice (Fourth Revision)",
        "edition": "Fourth Revision",
        "document_type": "standard",
        "domain": "construction_civil",
        "category": "concrete_aggregates",
        "product_type": "plain_reinforced_concrete_code",
        "pub_date": "2000-07-01",
        "valid_from": "2000-07-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is456_2000",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is456_2000.pdf",
        "authority": "Bureau of Indian Standards (CED 02)",
        "content_summary": "General structural safety, limit state design, characteristic compressive strength (M15 to M80), minimum cover, and durability clauses.",
    },
    {
        "standard_number": "IS 800 : 2007",
        "title": "General Construction in Steel — Code of Practice (Third Revision)",
        "edition": "Third Revision",
        "document_type": "standard",
        "domain": "construction_civil",
        "category": "steel_metals",
        "product_type": "structural_steel_code",
        "pub_date": "2007-12-01",
        "valid_from": "2007-12-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is800_2007",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is800_2007.pdf",
        "authority": "Bureau of Indian Standards (CED 07)",
        "content_summary": "Limit state method for structural steelwork, member design in tension, compression, flexure, bolted and welded connection design.",
    },
    {
        "standard_number": "IS 1077 : 1992",
        "title": "Common Burnt Clay Building Bricks — Specification (Fifth Revision)",
        "edition": "Fifth Revision",
        "document_type": "standard",
        "domain": "construction_civil",
        "category": "masonry_blocks",
        "product_type": "burnt_clay_bricks",
        "pub_date": "1992-06-01",
        "valid_from": "1992-06-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is1077_1992",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is1077_1992.pdf",
        "authority": "Bureau of Indian Standards (CED 30)",
        "content_summary": "Compressive strength classes 3.5 to 35 N/mm², water absorption not more than 20% by mass, and efflorescence rating.",
    },
    {
        "standard_number": "IS 2185 (Part 1) : 2005",
        "title": "Concrete Masonry Units — Specification — Part 1: Hollow and Solid Concrete Blocks (Third Revision)",
        "edition": "Third Revision",
        "document_type": "standard",
        "domain": "construction_civil",
        "category": "masonry_blocks",
        "product_type": "concrete_masonry_units",
        "pub_date": "2005-09-01",
        "valid_from": "2005-09-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is2185_1_2005",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is2185_1_2005.pdf",
        "authority": "Bureau of Indian Standards (CED 30)",
        "content_summary": "Grade A (load-bearing), Grade B (load-bearing non-exposed), and Grade C (non-load-bearing) blocks, minimum density and block compressive strength.",
    },
    {
        "standard_number": "IS 15658 : 2006",
        "title": "Precast Concrete Blocks for Paving — Specification (First Edition)",
        "edition": "First Edition",
        "document_type": "standard",
        "domain": "construction_civil",
        "category": "concrete_aggregates",
        "product_type": "precast_paver_blocks",
        "pub_date": "2006-02-01",
        "valid_from": "2006-02-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is15658_2006",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is15658_2006.pdf",
        "authority": "Bureau of Indian Standards (CED 02)",
        "content_summary": "Interlocking paver blocks for pedestrian and heavy traffic, compressive strength (M30 to M55), water absorption ≤ 6%, and abrasion resistance.",
    },
    {
        "standard_number": "IS 432 (Part 1) : 1982",
        "title": "Specification for Mild Steel and Medium Tensile Steel Bars and Hard-Drawn Steel Wire for Concrete Reinforcement — Part 1: Mild Steel and Medium Tensile Steel Bars",
        "edition": "Third Revision",
        "document_type": "standard",
        "domain": "construction_civil",
        "category": "steel_metals",
        "product_type": "mild_steel_bars",
        "pub_date": "1982-08-01",
        "valid_from": "1982-08-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is432_1_1982",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is432_1_1982.pdf",
        "authority": "Bureau of Indian Standards (CED 54)",
        "content_summary": "Mild steel Grade I and Grade II bars, yield stress ≥ 250 MPa, tensile strength ≥ 410 MPa, bend and rebend tests.",
    },
    {
        "standard_number": "IS 13920 : 2016",
        "title": "Ductile Design and Detailing of Reinforced Concrete Structures Subjected to Seismic Forces — Code of Practice (First Revision)",
        "edition": "First Revision",
        "document_type": "standard",
        "domain": "construction_civil",
        "category": "concrete_aggregates",
        "product_type": "ductile_detailing_concrete",
        "pub_date": "2016-03-01",
        "valid_from": "2016-03-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is13920_2016",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is13920_2016.pdf",
        "authority": "Bureau of Indian Standards (CED 39)",
        "content_summary": "Seismic ductile detailing provisions for flexural members, columns, beam-column joints, shear walls, and lap splices with confinement hoops.",
    },
    {
        "standard_number": "IS 1893 (Part 1) : 2016",
        "title": "Criteria for Earthquake Resistant Design of Structures — Part 1: General Provisions and Buildings (Sixth Revision)",
        "edition": "Sixth Revision",
        "document_type": "standard",
        "domain": "construction_civil",
        "category": "concrete_aggregates",
        "product_type": "earthquake_resistant_design",
        "pub_date": "2016-12-01",
        "valid_from": "2016-12-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is1893_1_2016",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is1893_1_2016.pdf",
        "authority": "Bureau of Indian Standards (CED 39)",
        "content_summary": "Design spectrum for seismic zones II, III, IV, and V, zone factor Z, importance factor I, response reduction factor R, and lateral drift limits.",
    },

    # 4. Food & Agriculture Domain (FAD Committees)
    {
        "standard_number": "IS 14543 : 2024",
        "title": "Packaged Drinking Water (Other Than Packaged Natural Mineral Water) — Specification (Third Revision)",
        "edition": "Third Revision",
        "document_type": "standard",
        "domain": "food_agriculture",
        "category": "drinking_water",
        "product_type": "packaged_drinking_water",
        "pub_date": "2024-04-01",
        "valid_from": "2024-04-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is14543_2024",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is14543_2024.pdf",
        "authority": "Bureau of Indian Standards (FAD 14)",
        "content_summary": "pH 6.5 to 8.5, TDS ≤ 500 mg/L, Turbidity ≤ 2 NTU, total coliforms absent in 250 mL.",
    },
    {
        "standard_number": "IS 13428 : 2005",
        "title": "Packaged Natural Mineral Water — Specification (Second Revision)",
        "edition": "Second Revision",
        "document_type": "standard",
        "domain": "food_agriculture",
        "category": "drinking_water",
        "product_type": "packaged_natural_mineral_water",
        "pub_date": "2005-08-01",
        "valid_from": "2005-08-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is13428_2005",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is13428_2005.pdf",
        "authority": "Bureau of Indian Standards (FAD 14)",
        "content_summary": "Natural source origin requirements, total dissolved solids, nitrate ≤ 45 mg/L, zero E. coli.",
    },
    {
        "standard_number": "IS 14433 : 2022",
        "title": "Infant Milk Substitutes — Specification (Second Revision)",
        "edition": "Second Revision",
        "document_type": "standard",
        "domain": "food_agriculture",
        "category": "dairy_products",
        "product_type": "infant_milk_substitutes",
        "pub_date": "2022-03-01",
        "valid_from": "2022-03-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is14433_2022",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is14433_2022.pdf",
        "authority": "Bureau of Indian Standards (FAD 19)",
        "content_summary": "Nutritional composition for infants, protein 10.5% to 15.0% by mass, milk fat ≥ 18%, bacterial count ≤ 10 000 CFU/g, zero coliforms.",
    },
    {
        "standard_number": "IS 11536 : 2007",
        "title": "Processed Cereal Based Complementary Foods for Infants — Specification (Second Revision)",
        "edition": "Second Revision",
        "document_type": "standard",
        "domain": "food_agriculture",
        "category": "dairy_products",
        "product_type": "cereal_based_infant_foods",
        "pub_date": "2007-06-01",
        "valid_from": "2007-06-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is11536_2007",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is11536_2007.pdf",
        "authority": "Bureau of Indian Standards (FAD 19)",
        "content_summary": "Cereal weaning foods, minimum protein 12.0%, carbohydrate content, dietary fiber, vitamin and mineral fortification limits.",
    },
    {
        "standard_number": "IS 2052 : 2009",
        "title": "Compounded Feeds for Cattle — Specification (Fifth Revision)",
        "edition": "Fifth Revision",
        "document_type": "standard",
        "domain": "food_agriculture",
        "category": "animal_feeds",
        "product_type": "compounded_cattle_feed",
        "pub_date": "2009-12-01",
        "valid_from": "2009-12-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is2052_2009",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is2052_2009.pdf",
        "authority": "Bureau of Indian Standards (FAD 05)",
        "content_summary": "Type I and Type II cattle feed, crude protein ≥ 20.0% (Type I), crude fat ≥ 2.5%, crude fiber ≤ 12.0%, aflatoxin B1 ≤ 20 ppb.",
    },
    {
        "standard_number": "IS 1165 : 2002",
        "title": "Milk Powder — Specification (Fifth Revision)",
        "edition": "Fifth Revision",
        "document_type": "standard",
        "domain": "food_agriculture",
        "category": "dairy_products",
        "product_type": "milk_powder",
        "pub_date": "2002-04-01",
        "valid_from": "2002-04-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is1165_2002",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is1165_2002.pdf",
        "authority": "Bureau of Indian Standards (FAD 19)",
        "content_summary": "Whole milk powder (fat ≥ 26.0%), partly skimmed milk powder, moisture ≤ 4.0%, titratable acidity ≤ 1.2%, solubility index ≤ 2.0 mL.",
    },
    {
        "standard_number": "IS 1166 : 2022",
        "title": "Condensed Milk, Partly Skimmed and Skimmed Condensed Milk — Specification (Third Revision)",
        "edition": "Third Revision",
        "document_type": "standard",
        "domain": "food_agriculture",
        "category": "dairy_products",
        "product_type": "condensed_milk",
        "pub_date": "2022-08-01",
        "valid_from": "2022-08-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is1166_2022",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is1166_2022.pdf",
        "authority": "Bureau of Indian Standards (FAD 19)",
        "content_summary": "Sweetened condensed milk, total milk solids ≥ 31.0%, milk fat ≥ 9.0%, sucrose 40% to 45%, accelerated storage stability.",
    },
    {
        "standard_number": "IS 1224 (Part 1) : 1977",
        "title": "Determination of Fat in Whole Milk, Evaporated Milk and Condensed Milk by Gerber Method — Part 1: Milk",
        "edition": "First Revision",
        "document_type": "standard",
        "domain": "food_agriculture",
        "category": "dairy_products",
        "product_type": "fat_in_milk_testing",
        "pub_date": "1977-09-01",
        "valid_from": "1977-09-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is1224_1_1977",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is1224_1_1977.pdf",
        "authority": "Bureau of Indian Standards (FAD 19)",
        "content_summary": "Gerber butyrometer test procedure, sulfuric acid density (1.815 g/mL), isoamyl alcohol reagent, and centrifugation method.",
    },
    {
        "standard_number": "IS 4079 : 1967",
        "title": "Specification for Canned Rasgulla (First Edition)",
        "edition": "First Edition",
        "document_type": "standard",
        "domain": "food_agriculture",
        "category": "confectionery_sweets",
        "product_type": "canned_rasgulla",
        "pub_date": "1967-08-01",
        "valid_from": "1967-08-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is4079_1967",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is4079_1967.pdf",
        "authority": "Bureau of Indian Standards (FAD 19)",
        "content_summary": "Chhana base confectionery in sugar syrup, drained weight ≥ 50% of net weight, sugar syrup concentration 45° to 55° Brix, fat ≥ 5.0%.",
    },
    {
        "standard_number": "IS 15757 : 2007",
        "title": "Follow-up Formula — Specification (First Edition)",
        "edition": "First Edition",
        "document_type": "standard",
        "domain": "food_agriculture",
        "category": "dairy_products",
        "product_type": "follow_up_formula",
        "pub_date": "2007-04-01",
        "valid_from": "2007-04-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is15757_2007",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is15757_2007.pdf",
        "authority": "Bureau of Indian Standards (FAD 19)",
        "content_summary": "Foods for infants from 6 months onwards, energy density 60 to 85 kcal/100 mL, linoleic acid, iron fortification, and hygienic safety.",
    },
    {
        "standard_number": "IS 544 : 2014",
        "title": "Groundnut Oil — Specification (Third Revision)",
        "edition": "Third Revision",
        "document_type": "standard",
        "domain": "food_agriculture",
        "category": "edible_oils_salts",
        "product_type": "groundnut_oil",
        "pub_date": "2014-05-01",
        "valid_from": "2014-05-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is544_2014",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is544_2014.pdf",
        "authority": "Bureau of Indian Standards (FAD 08)",
        "content_summary": "Refined and raw groundnut oil, refractive index (1.4620 to 1.4640 at 40°C), saponification value 188 to 196, iodine value 85 to 99, acid value ≤ 0.5.",
    },
    {
        "standard_number": "IS 4277 : 2014",
        "title": "Mustard Oil — Specification (Third Revision)",
        "edition": "Third Revision",
        "document_type": "standard",
        "domain": "food_agriculture",
        "category": "edible_oils_salts",
        "product_type": "mustard_oil",
        "pub_date": "2014-06-01",
        "valid_from": "2014-06-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is4277_2014",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is4277_2014.pdf",
        "authority": "Bureau of Indian Standards (FAD 08)",
        "content_summary": "Mustard seed oil and rapessed oil, refractive index (1.4646 to 1.4662), allyl isothiocyanate content 0.25% to 0.60%, zero argemone oil.",
    },
    {
        "standard_number": "IS 7224 : 2006",
        "title": "Iodized Salt — Specification (Third Revision)",
        "edition": "Third Revision",
        "document_type": "standard",
        "domain": "food_agriculture",
        "category": "edible_oils_salts",
        "product_type": "iodized_salt",
        "pub_date": "2006-03-01",
        "valid_from": "2006-03-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is7224_2006",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is7224_2006.pdf",
        "authority": "Bureau of Indian Standards (FAD 08)",
        "content_summary": "Edible common salt fortified with potassium iodate, sodium chloride ≥ 96.0%, iodine content ≥ 30 ppm (production) and ≥ 15 ppm (retail).",
    },
    {
        "standard_number": "IS 10083 : 1982",
        "title": "Code of Practice for Installation and Maintenance of Tube Wells for Food and Agricultural Purposes",
        "edition": "First Edition",
        "document_type": "standard",
        "domain": "food_agriculture",
        "category": "agricultural_equipment",
        "product_type": "agricultural_tube_wells",
        "pub_date": "1982-11-01",
        "valid_from": "1982-11-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is10083_1982",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is10083_1982.pdf",
        "authority": "Bureau of Indian Standards (FAD 20)",
        "content_summary": "Design, drilling, gravel packing, development, yield testing, and disinfection of agricultural tube wells.",
    },
    {
        "standard_number": "IS 5949 : 1990",
        "title": "Determination of Nitrogen and Protein in Food Products by Kjeldahl Method (First Revision)",
        "edition": "First Revision",
        "document_type": "standard",
        "domain": "food_agriculture",
        "category": "food_analysis_methods",
        "product_type": "nitrogen_protein_kjeldahl",
        "pub_date": "1990-10-01",
        "valid_from": "1990-10-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is5949_1990",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is5949_1990.pdf",
        "authority": "Bureau of Indian Standards (FAD 19)",
        "content_summary": "Digestion using sulfuric acid with copper sulfate/potassium sulfate catalyst, distillation into boric acid, and titration for total crude protein.",
    },

    # 5. Mechanical & Automotive Domain (MED Committees)
    {
        "standard_number": "IS 2347 : 2017",
        "title": "Domestic Pressure Cookers — Specification (Fifth Revision)",
        "edition": "Fifth Revision",
        "document_type": "standard",
        "domain": "mechanical_automotive",
        "category": "domestic_appliances_gas",
        "product_type": "domestic_pressure_cookers",
        "pub_date": "2017-03-01",
        "valid_from": "2017-03-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is2347_2017",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is2347_2017.pdf",
        "authority": "Bureau of Indian Standards (MED 33)",
        "content_summary": "Hydraulic proof burst pressure ≥ 3.0 bar (300 kPa), operating pressure 1.0 bar (100 kPa), fusible safety plug operating at 1.5 to 2.0 bar.",
    },
    {
        "standard_number": "IS 4246 : 2002",
        "title": "Domestic Gas Stoves for Use with Liquefied Petroleum Gases — Specification (Fifth Revision)",
        "edition": "Fifth Revision",
        "document_type": "standard",
        "domain": "mechanical_automotive",
        "category": "domestic_appliances_gas",
        "product_type": "domestic_gas_stoves_lpg",
        "pub_date": "2002-12-01",
        "valid_from": "2002-12-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is4246_2002",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is4246_2002.pdf",
        "authority": "Bureau of Indian Standards (MED 33)",
        "content_summary": "Thermal efficiency ≥ 68%, CO/CO2 ratio ≤ 0.02 in combustion products, gas soundness test at 15 kPa.",
    },
    {
        "standard_number": "IS 15683 : 2018",
        "title": "Portable Fire Extinguishers — Performance and Construction — Specification (First Revision)",
        "edition": "First Revision",
        "document_type": "standard",
        "domain": "mechanical_automotive",
        "category": "fire_safety",
        "product_type": "portable_fire_extinguishers",
        "pub_date": "2018-04-01",
        "valid_from": "2018-04-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is15683_2018",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is15683_2018.pdf",
        "authority": "Bureau of Indian Standards (CED 22)",
        "content_summary": "Rating fire performance Class A, B, C, D, and F fires, burst test pressure ≥ 2.7 times working pressure, effective discharge duration.",
    },
    {
        "standard_number": "IS 2878 : 2004",
        "title": "Fire Extinguisher, Carbon Dioxide Type (Portable and Trolley Mounted) — Specification (Third Revision)",
        "edition": "Third Revision",
        "document_type": "standard",
        "domain": "mechanical_automotive",
        "category": "fire_safety",
        "product_type": "co2_fire_extinguishers",
        "pub_date": "2004-05-01",
        "valid_from": "2004-05-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is2878_2004",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is2878_2004.pdf",
        "authority": "Bureau of Indian Standards (CED 22)",
        "content_summary": "CO2 gas charge filling ratio ≤ 0.667, seamless steel cylinder hydraulic test pressure of 25 MPa, discharge horn with non-conductive handle.",
    },
    {
        "standard_number": "IS 940 : 2003",
        "title": "Portable Fire Extinguishers, Water Type (Gas Cartridge) — Specification (Fourth Revision)",
        "edition": "Fourth Revision",
        "document_type": "standard",
        "domain": "mechanical_automotive",
        "category": "fire_safety",
        "product_type": "water_fire_extinguishers",
        "pub_date": "2003-07-01",
        "valid_from": "2003-07-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is940_2003",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is940_2003.pdf",
        "authority": "Bureau of Indian Standards (CED 22)",
        "content_summary": "9-litre capacity water type extinguishers, minimum 95% discharge within 60 to 120 seconds, hydraulic stretch test at 3.0 MPa.",
    },
    {
        "standard_number": "IS 12254 : 1993",
        "title": "Polyvinyl Chloride (PVC) Industrial Boots — Specification (Second Revision)",
        "edition": "Second Revision",
        "document_type": "standard",
        "domain": "mechanical_automotive",
        "category": "personal_protective_equipment",
        "product_type": "pvc_industrial_boots",
        "pub_date": "1993-06-01",
        "valid_from": "1993-06-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is12254_1993",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is12254_1993.pdf",
        "authority": "Bureau of Indian Standards (TXD 35)",
        "content_summary": "Moulded PVC safety boots, tensile strength of upper material ≥ 10.0 MPa, flexing resistance without cracking after 150 000 flexes.",
    },
    {
        "standard_number": "IS 13745 : 1993",
        "title": "Non-refillable Metallic Containers for Liquefied Petroleum Gas — Specification (First Edition)",
        "edition": "First Edition",
        "document_type": "standard",
        "domain": "mechanical_automotive",
        "category": "domestic_appliances_gas",
        "product_type": "non_refillable_lpg_containers",
        "pub_date": "1993-11-01",
        "valid_from": "1993-11-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is13745_1993",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is13745_1993.pdf",
        "authority": "Bureau of Indian Standards (MED 16)",
        "content_summary": "Disposable LPG cartridges and small metallic cans, test pressure 1.5 MPa, burst pressure ≥ 2.0 MPa, leakage testing at 55°C water bath.",
    },
    {
        "standard_number": "IS 14842 : 2000",
        "title": "Steel Wire Ropes for General Engineering Purposes — Specification (First Edition)",
        "edition": "First Edition",
        "document_type": "standard",
        "domain": "mechanical_automotive",
        "category": "engineering_components",
        "product_type": "steel_wire_ropes",
        "pub_date": "2000-09-01",
        "valid_from": "2000-09-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is14842_2000",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is14842_2000.pdf",
        "authority": "Bureau of Indian Standards (MED 10)",
        "content_summary": "Round strand steel wire ropes, tensile strength grades 1570, 1770 and 1960 N/mm², minimum breaking force, and reverse bend test on wires.",
    },
    {
        "standard_number": "IS 3601 : 2006",
        "title": "Steel Tubes for Mechanical and General Engineering Purposes — Specification (Third Revision)",
        "edition": "Third Revision",
        "document_type": "standard",
        "domain": "mechanical_automotive",
        "category": "engineering_components",
        "product_type": "steel_tubes_mechanical",
        "pub_date": "2006-05-01",
        "valid_from": "2006-05-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is3601_2006",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is3601_2006.pdf",
        "authority": "Bureau of Indian Standards (MED 10)",
        "content_summary": "Seamless and welded carbon steel tubes, designations WTSt 310 to WTSt 510, flattening test, expanding test, and dimensional tolerances.",
    },
    {
        "standard_number": "IS 1978 : 1982",
        "title": "Specification for Line Pipe (Second Revision)",
        "edition": "Second Revision",
        "document_type": "standard",
        "domain": "mechanical_automotive",
        "category": "piping_flow_systems",
        "product_type": "line_pipes_oil_gas",
        "pub_date": "1982-12-01",
        "valid_from": "1982-12-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is1978_1982",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is1978_1982.pdf",
        "authority": "Bureau of Indian Standards (MED 16)",
        "content_summary": "Seamless and welded steel line pipe for conveyance of gas, water and oil in petroleum and natural gas industries, hydrostatic test pressure.",
    },
    {
        "standard_number": "IS 779 : 1994",
        "title": "Water Meters (Domestic Type) — Specification (Sixth Revision)",
        "edition": "Sixth Revision",
        "document_type": "standard",
        "domain": "mechanical_automotive",
        "category": "piping_flow_systems",
        "product_type": "domestic_water_meters",
        "pub_date": "1994-08-01",
        "valid_from": "1994-08-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is779_1994",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is779_1994.pdf",
        "authority": "Bureau of Indian Standards (MED 32)",
        "content_summary": "Nominal sizes 15 mm to 50 mm, Class A and Class B accuracy, maximum permissible error ±2% in upper flow zone and ±5% in lower zone.",
    },
    {
        "standard_number": "IS 903 : 1993",
        "title": "Fire Hose Delivery Couplings, Branch Pipe, Nozzles and Strainer — Specification (Fourth Revision)",
        "edition": "Fourth Revision",
        "document_type": "standard",
        "domain": "mechanical_automotive",
        "category": "fire_safety",
        "product_type": "fire_hose_couplings",
        "pub_date": "1993-04-01",
        "valid_from": "1993-04-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is903_1993",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is903_1993.pdf",
        "authority": "Bureau of Indian Standards (CED 22)",
        "content_summary": "Instantaneous pattern delivery couplings (63 mm), bronze and aluminium alloy materials, hydraulic proof pressure of 2.1 MPa for 2.5 minutes.",
    },
    {
        "standard_number": "IS 513 (Part 1) : 2016",
        "title": "Cold Reduced Carbon Steel Sheet and Strip — Part 1: Cold Forming and Drawing Steel (Sixth Revision)",
        "edition": "Sixth Revision",
        "document_type": "standard",
        "domain": "mechanical_automotive",
        "category": "sheet_metal_metallurgy",
        "product_type": "cold_reduced_steel_sheets",
        "pub_date": "2016-07-01",
        "valid_from": "2016-07-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is513_1_2016",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is513_1_2016.pdf",
        "authority": "Bureau of Indian Standards (MTD 04)",
        "content_summary": "Grades CR1 (commercial), CR2 (drawing), CR3 (deep drawing), and CR4 (extra deep drawing), Erichsen cupping test value, and yield stress.",
    },
    {
        "standard_number": "IS 1079 : 2017",
        "title": "Hot Rolled Carbon Steel Sheet and Strip — Specification (Sixth Revision)",
        "edition": "Sixth Revision",
        "document_type": "standard",
        "domain": "mechanical_automotive",
        "category": "sheet_metal_metallurgy",
        "product_type": "hot_rolled_steel_sheets",
        "pub_date": "2017-08-01",
        "valid_from": "2017-08-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is1079_2017",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is1079_2017.pdf",
        "authority": "Bureau of Indian Standards (MTD 04)",
        "content_summary": "Grades HR1 to HR5, tensile strength (270 to 440 MPa), minimum elongation (23% to 38%), bend test around pin diameter.",
    },
    {
        "standard_number": "IS 814 : 2004",
        "title": "Covered Electrodes for Manual Metal Arc Welding of Carbon and Carbon Manganese Steel — Specification (Sixth Revision)",
        "edition": "Sixth Revision",
        "document_type": "standard",
        "domain": "mechanical_automotive",
        "category": "welding_fabrication",
        "product_type": "manual_metal_arc_electrodes",
        "pub_date": "2004-10-01",
        "valid_from": "2004-10-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is814_2004",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is814_2004.pdf",
        "authority": "Bureau of Indian Standards (MTD 11)",
        "content_summary": "Electrode classification coding (e.g. E5112X), all-weld metal tensile strength (410 to 510 MPa), yield strength ≥ 330 MPa, Charpy V-notch impact energy ≥ 27 J.",
    },

    # 6. Medical & Safety Domain (MHD & CHD Committees)
    {
        "standard_number": "IS 4151 : 2015",
        "title": "Protective Helmets for Two Wheeler Riders — Specification (Fourth Revision)",
        "edition": "Fourth Revision",
        "document_type": "standard",
        "domain": "medical_safety",
        "category": "personal_protective_equipment",
        "product_type": "protective_helmets_motorcycle",
        "pub_date": "2015-09-01",
        "valid_from": "2015-09-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is4151_2015",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is4151_2015.pdf",
        "authority": "Bureau of Indian Standards (MHD 22)",
        "content_summary": "Peak headform deceleration ≤ 300 g during 2.5 m drop test, retention system dynamic displacement ≤ 25 mm, max mass ≤ 1500 g.",
    },
    {
        "standard_number": "IS 15298 (Part 2) : 2016",
        "title": "Personal Protective Equipment — Safety Footwear (Second Revision)",
        "edition": "Second Revision",
        "document_type": "standard",
        "domain": "medical_safety",
        "category": "personal_protective_equipment",
        "product_type": "safety_footwear",
        "pub_date": "2016-04-01",
        "valid_from": "2016-04-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is15298_2_2016",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is15298_2_2016.pdf",
        "authority": "Bureau of Indian Standards (MHD 22)",
        "content_summary": "Steel toecap impact resistance of 200 J with minimum clearance under toecap ≥ 14.0 mm for size 8.",
    },
    {
        "standard_number": "IS 13422 : 1992",
        "title": "Sterile Rubber Surgical Gloves — Specification (First Edition)",
        "edition": "First Edition",
        "document_type": "standard",
        "domain": "medical_safety",
        "category": "personal_protective_equipment",
        "product_type": "surgical_rubber_gloves",
        "pub_date": "1992-05-01",
        "valid_from": "1992-05-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is13422_1992",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is13422_1992.pdf",
        "authority": "Bureau of Indian Standards (MHD 12)",
        "content_summary": "Natural rubber latex surgical gloves, tensile strength ≥ 24.0 MPa before ageing and ≥ 18.0 MPa after accelerated ageing, sterility testing.",
    },
    {
        "standard_number": "IS 9473 : 2002",
        "title": "Respiratory Protective Devices — Filtering Half Masks to Protect Against Particles — Specification (First Revision)",
        "edition": "First Revision",
        "document_type": "standard",
        "domain": "medical_safety",
        "category": "personal_protective_equipment",
        "product_type": "respiratory_masks_ffp2",
        "pub_date": "2002-08-01",
        "valid_from": "2002-08-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is9473_2002",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is9473_2002.pdf",
        "authority": "Bureau of Indian Standards (CHD 21)",
        "content_summary": "FFP1 (80%), FFP2 (94%), and FFP3 (99%) filtration efficiency against sodium chloride and paraffin oil aerosols, breathing resistance limits.",
    },
    {
        "standard_number": "IS 2925 : 1984",
        "title": "Industrial Safety Helmets — Specification (Second Revision)",
        "edition": "Second Revision",
        "document_type": "standard",
        "domain": "medical_safety",
        "category": "personal_protective_equipment",
        "product_type": "industrial_safety_helmets",
        "pub_date": "1984-06-01",
        "valid_from": "1984-06-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is2925_1984",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is2925_1984.pdf",
        "authority": "Bureau of Indian Standards (CED 22)",
        "content_summary": "Shock absorption test (transmitted force ≤ 5.0 kN), penetration resistance, electrical resistance (leakage current ≤ 3.0 mA at 1.2 kV), flammability.",
    },
    {
        "standard_number": "IS 3521 (Part 1) : 2021",
        "title": "Personal Protective Equipment — Safety Belts and Harnesses — Part 1: Full Body Harness",
        "edition": "Fourth Revision",
        "document_type": "standard",
        "domain": "medical_safety",
        "category": "personal_protective_equipment",
        "product_type": "safety_belts_harnesses",
        "pub_date": "2021-03-01",
        "valid_from": "2021-03-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is3521_1_2021",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is3521_1_2021.pdf",
        "authority": "Bureau of Indian Standards (CHD 21)",
        "content_summary": "Full body harnesses for fall arrest, static strength test (≥ 15 kN for 3 minutes), dynamic performance drop test with 100 kg torso dummy.",
    },
    {
        "standard_number": "IS 6994 (Part 1) : 1973",
        "title": "Specification for Industrial Safety Gloves — Part 1: Leather and Cotton Gloves",
        "edition": "First Edition",
        "document_type": "standard",
        "domain": "medical_safety",
        "category": "personal_protective_equipment",
        "product_type": "industrial_safety_gloves",
        "pub_date": "1973-10-01",
        "valid_from": "1973-10-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is6994_1_1973",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is6994_1_1973.pdf",
        "authority": "Bureau of Indian Standards (CHD 21)",
        "content_summary": "Leather and fabric work gloves, tear strength, puncture resistance, dimensional sizing, and seams integrity.",
    },
    {
        "standard_number": "IS 5983 : 1980",
        "title": "Specification for Eye-Protectors (First Revision)",
        "edition": "First Revision",
        "document_type": "standard",
        "domain": "medical_safety",
        "category": "personal_protective_equipment",
        "product_type": "eye_protectors_goggles",
        "pub_date": "1980-12-01",
        "valid_from": "1980-12-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is5983_1980",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is5983_1980.pdf",
        "authority": "Bureau of Indian Standards (CHD 21)",
        "content_summary": "Industrial eye protectors, optical quality class, impact resistance (steel ball drop at 5.1 m/s), resistance to ignition and UV radiation.",
    },
    {
        "standard_number": "IS 16289 : 2014",
        "title": "Medical Face Masks — Specification (First Edition)",
        "edition": "First Edition",
        "document_type": "standard",
        "domain": "medical_safety",
        "category": "medical_textiles",
        "product_type": "medical_face_masks_surgical",
        "pub_date": "2014-04-01",
        "valid_from": "2014-04-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is16289_2014",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is16289_2014.pdf",
        "authority": "Bureau of Indian Standards (TXD 36)",
        "content_summary": "Surgical masks Type I, Type II, and Type IIR, bacterial filtration efficiency (BFE ≥ 95% for Type I, ≥ 98% for Type II/IIR), differential pressure.",
    },
    {
        "standard_number": "IS 17423 : 2020",
        "title": "Coveralls for Healthcare Personnel — Specification (First Edition)",
        "edition": "First Edition",
        "document_type": "standard",
        "domain": "medical_safety",
        "category": "medical_textiles",
        "product_type": "coveralls_healthcare",
        "pub_date": "2020-05-01",
        "valid_from": "2020-05-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is17423_2020",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is17423_2020.pdf",
        "authority": "Bureau of Indian Standards (TXD 36)",
        "content_summary": "Personal protective coveralls, synthetic blood penetration resistance (Class 1 to Class 6 / ISO 16603), seam strength ≥ 100 N.",
    },
    {
        "standard_number": "IS 13450 (Part 1) : 2018",
        "title": "Medical Electrical Equipment — Part 1: General Requirements for Basic Safety and Essential Performance",
        "edition": "Third Revision",
        "document_type": "standard",
        "domain": "medical_safety",
        "category": "medical_electrical_equipment",
        "product_type": "medical_electrical_equipment_general",
        "pub_date": "2018-09-01",
        "valid_from": "2018-09-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is13450_1_2018",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is13450_1_2018.pdf",
        "authority": "Bureau of Indian Standards (MHD 15)",
        "content_summary": "Protection against electrical hazards, earth leakage current ≤ 5.0 mA, patient leakage current ≤ 10 µA (Type CF), dielectric strength.",
    },
    {
        "standard_number": "IS 13450 (Part 2/Sec 24) : 2019",
        "title": "Medical Electrical Equipment — Part 2-24: Particular Requirements for the Basic Safety of Infusion Pumps and Controllers",
        "edition": "First Edition",
        "document_type": "standard",
        "domain": "medical_safety",
        "category": "medical_electrical_equipment",
        "product_type": "infusion_pumps",
        "pub_date": "2019-07-01",
        "valid_from": "2019-07-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is13450_2_24_2019",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is13450_2_24_2019.pdf",
        "authority": "Bureau of Indian Standards (MHD 15)",
        "content_summary": "Volumetric accuracy ±5%, occlusion alarm pressure limit, air-in-line detector sensitivity, and free-flow protection mechanism.",
    },
    {
        "standard_number": "IS 13450 (Part 2/Sec 37) : 2018",
        "title": "Medical Electrical Equipment — Part 2-37: Particular Requirements for the Safety of Ultrasonic Medical Diagnostic Equipment",
        "edition": "Second Revision",
        "document_type": "standard",
        "domain": "medical_safety",
        "category": "medical_electrical_equipment",
        "product_type": "ultrasonic_diagnostic_equipment",
        "pub_date": "2018-06-01",
        "valid_from": "2018-06-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is13450_2_37_2018",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is13450_2_37_2018.pdf",
        "authority": "Bureau of Indian Standards (MHD 15)",
        "content_summary": "Acoustic output indices (Mechanical Index MI ≤ 1.9, Thermal Index TIS/TIB ≤ 6.0), transducer surface temperature limits (≤ 43°C in contact with patient).",
    },
    {
        "standard_number": "IS 7620 (Part 1) : 1986",
        "title": "Diagnostic Medical X-Ray Equipment — Part 1: General and Safety Requirements (First Revision)",
        "edition": "First Revision",
        "document_type": "standard",
        "domain": "medical_safety",
        "category": "medical_electrical_equipment",
        "product_type": "diagnostic_x_ray_equipment",
        "pub_date": "1986-08-01",
        "valid_from": "1986-08-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is7620_1_1986",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is7620_1_1986.pdf",
        "authority": "Bureau of Indian Standards (MHD 15)",
        "content_summary": "Radiation leakage from tube housing ≤ 1.0 mGy in 1 hour at 1 meter, total filtration ≥ 2.5 mm Al equivalent at 100 kV, reproducibility of exposure.",
    },
    {
        "standard_number": "IS 8607 : 1977",
        "title": "Specification for Wheelchairs, Folding, Adult Size (First Edition)",
        "edition": "First Edition",
        "document_type": "standard",
        "domain": "medical_safety",
        "category": "assistive_mobility_devices",
        "product_type": "wheelchairs_manual_powered",
        "pub_date": "1977-04-01",
        "valid_from": "1977-04-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is8607_1977",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is8607_1977.pdf",
        "authority": "Bureau of Indian Standards (MHD 10)",
        "content_summary": "Static load test (occupant mass 100 kg), fatigue resistance on rotating drum with obstacles, parking brake holding on 10° incline.",
    },

    # 7. Chemicals & Materials Domain (CHD Committees)
    {
        "standard_number": "IS 15489 : 2004",
        "title": "Plastic Emulsion Paint — Specification (First Revision)",
        "edition": "First Revision",
        "document_type": "standard",
        "domain": "chemicals_materials",
        "category": "paints_coatings",
        "product_type": "plastic_emulsion_paint",
        "pub_date": "2004-07-01",
        "valid_from": "2004-07-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is15489_2004",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is15489_2004.pdf",
        "authority": "Bureau of Indian Standards (CHD 20)",
        "content_summary": "Lead content ≤ 90 ppm, wet scrub resistance ≥ 1000 cycles, drying time surface dry ≤ 30 min.",
    },
    {
        "standard_number": "IS 4985 : 2021",
        "title": "Unplasticized Polyvinyl Chloride (UPVC) Pipes for Potable Water Supplies — Specification (Fourth Revision)",
        "edition": "Fourth Revision",
        "document_type": "standard",
        "domain": "chemicals_materials",
        "category": "polymers_pipes",
        "product_type": "upvc_pipes_potable_water",
        "pub_date": "2021-05-01",
        "valid_from": "2021-05-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is4985_2021",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is4985_2021.pdf",
        "authority": "Bureau of Indian Standards (CED 50)",
        "content_summary": "Hydrostatic design pressure testing for 1 000 h at 20°C and opacity test ≥ 99.8%.",
    },
    {
        "standard_number": "IS 12235 (Part 1) : 2004",
        "title": "Thermoplastics Pipes and Fittings — Methods of Test — Part 1: Measurement of Dimensions",
        "edition": "Second Revision",
        "document_type": "standard",
        "domain": "chemicals_materials",
        "category": "polymers_pipes",
        "product_type": "thermoplastics_pipes_tests",
        "pub_date": "2004-03-01",
        "valid_from": "2004-03-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is12235_1_2004",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is12235_1_2004.pdf",
        "authority": "Bureau of Indian Standards (CED 50)",
        "content_summary": "Standardized test methods for wall thickness, mean outside diameter, out-of-roundness, and length measurement.",
    },
    {
        "standard_number": "IS 1239 (Part 1) : 2004",
        "title": "Steel Tubes, Tubulars and Other Wrought Steel Fittings — Part 1: Steel Tubes (Sixth Revision)",
        "edition": "Sixth Revision",
        "document_type": "standard",
        "domain": "chemicals_materials",
        "category": "polymers_pipes",
        "product_type": "mild_steel_tubes",
        "pub_date": "2004-08-01",
        "valid_from": "2004-08-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is1239_1_2004",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is1239_1_2004.pdf",
        "authority": "Bureau of Indian Standards (CED 54)",
        "content_summary": "Mild steel tubes for water, gas and air conveyance, cold bend test, flattening test, and hydrostatic test pressure of 5 MPa.",
    },
    {
        "standard_number": "IS 12701 : 1996",
        "title": "Rotomoulded Polyethylene Water Storage Tanks — Specification (First Revision)",
        "edition": "First Revision",
        "document_type": "standard",
        "domain": "chemicals_materials",
        "category": "polymers_pipes",
        "product_type": "hdpe_water_tanks",
        "pub_date": "1996-09-01",
        "valid_from": "1996-09-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is12701_1996",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is12701_1996.pdf",
        "authority": "Bureau of Indian Standards (CED 50)",
        "content_summary": "UV stabilization with carbon black or pigments, overall wall thickness, impact resistance, and deformation test under water load.",
    },
    {
        "standard_number": "IS 13592 : 2013",
        "title": "Unplasticized Polyvinyl Chloride (UPVC) Pipes for Soil and Waste Discharge Systems Inside Buildings (First Revision)",
        "edition": "First Revision",
        "document_type": "standard",
        "domain": "chemicals_materials",
        "category": "polymers_pipes",
        "product_type": "soil_waste_pipes",
        "pub_date": "2013-05-01",
        "valid_from": "2013-05-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is13592_2013",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is13592_2013.pdf",
        "authority": "Bureau of Indian Standards (CED 50)",
        "content_summary": "Type A (ventilation/rainwater) and Type B (soil/waste) pipes, stress relief test, impact strength at 0°C, and ring stiffness.",
    },
    {
        "standard_number": "IS 14885 : 2001",
        "title": "Polyethylene Pipes for the Supply of Gaseous Fuels — Specification (First Edition)",
        "edition": "First Edition",
        "document_type": "standard",
        "domain": "chemicals_materials",
        "category": "polymers_pipes",
        "product_type": "gas_polyethylene_pipes",
        "pub_date": "2001-06-01",
        "valid_from": "2001-06-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is14885_2001",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is14885_2001.pdf",
        "authority": "Bureau of Indian Standards (CED 50)",
        "content_summary": "High density PE 80 and PE 100 for city gas distribution, resistance to rapid crack propagation (RCP), and melt flow rate.",
    },
    {
        "standard_number": "IS 3196 (Part 1) : 2006",
        "title": "Welded Low Carbon Steel Cylinders for Low Pressure Liquefiable Gases — Part 1: Cylinders for LPG",
        "edition": "Fifth Revision",
        "document_type": "standard",
        "domain": "chemicals_materials",
        "category": "industrial_gas_cylinders",
        "product_type": "welded_lpg_cylinders",
        "pub_date": "2006-11-01",
        "valid_from": "2006-11-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is3196_1_2006",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is3196_1_2006.pdf",
        "authority": "Bureau of Indian Standards (MED 16)",
        "content_summary": "Design, manufacture and testing of domestic LPG cylinders, minimum calculated wall thickness, hydrostatic stretch test, and burst pressure.",
    },
    {
        "standard_number": "IS 15633 : 2005",
        "title": "Automotive Vehicles — Pneumatic Tyres for Passenger Car Vehicles — Diagonal and Radial Ply",
        "edition": "First Edition",
        "document_type": "standard",
        "domain": "chemicals_materials",
        "category": "tyres_tubes",
        "product_type": "automotive_pneumatic_tyres",
        "pub_date": "2005-12-01",
        "valid_from": "2005-12-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is15633_2005",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is15633_2005.pdf",
        "authority": "Bureau of Indian Standards (TED 07)",
        "content_summary": "Load/speed performance test, tyre bead unseating resistance, breaking energy strength test, and dimensional parameters.",
    },
    {
        "standard_number": "IS 15636 : 2012",
        "title": "Automotive Vehicles — Pneumatic Tyres for Commercial Vehicles — Diagonal and Radial Ply (First Revision)",
        "edition": "First Revision",
        "document_type": "standard",
        "domain": "chemicals_materials",
        "category": "tyres_tubes",
        "product_type": "commercial_vehicle_tyres",
        "pub_date": "2012-08-01",
        "valid_from": "2012-08-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is15636_2012",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is15636_2012.pdf",
        "authority": "Bureau of Indian Standards (TED 07)",
        "content_summary": "High endurance testing on test drum, minimum plunger breaking energy, load capacity ratings, and speed symbol validation.",
    },
    {
        "standard_number": "IS 10500 : 2012",
        "title": "Drinking Water — Specification (Second Revision)",
        "edition": "Second Revision",
        "document_type": "standard",
        "domain": "chemicals_materials",
        "category": "water_specifications",
        "product_type": "drinking_water_specification",
        "pub_date": "2012-05-01",
        "valid_from": "2012-05-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is10500_2012",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is10500_2012.pdf",
        "authority": "Bureau of Indian Standards (FAD 14)",
        "content_summary": "Acceptable and permissible limits: pH 6.5-8.5, TDS 500-2000 mg/L, Total Hardness 200-600 mg/L, Fluoride 1.0-1.5 mg/L, Arsenic 0.01-0.05 mg/L.",
    },
    {
        "standard_number": "IS 15477 : 2019",
        "title": "Adhesives for Use with Ceramic, Mosaic and Stone Tiles — Specification (Second Revision)",
        "edition": "Second Revision",
        "document_type": "standard",
        "domain": "chemicals_materials",
        "category": "adhesives_waterproofing",
        "product_type": "tile_adhesives",
        "pub_date": "2019-09-01",
        "valid_from": "2019-09-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is15477_2019",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is15477_2019.pdf",
        "authority": "Bureau of Indian Standards (CED 55)",
        "content_summary": "Type 1 to Type 4 adhesive classifications, tensile adhesion strength (≥1.0 N/mm²), shear adhesion strength, and open time.",
    },
    {
        "standard_number": "IS 3067 : 1988",
        "title": "Code of Practice for General Design Details and Preparatory Work for Damp-Proofing and Waterproofing of Buildings (First Revision)",
        "edition": "First Revision",
        "document_type": "standard",
        "domain": "chemicals_materials",
        "category": "adhesives_waterproofing",
        "product_type": "waterproofing_buildings",
        "pub_date": "1988-10-01",
        "valid_from": "1988-10-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is3067_1988",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is3067_1988.pdf",
        "authority": "Bureau of Indian Standards (CED 41)",
        "content_summary": "Bituminous, polymer-modified, and elastomeric membrane waterproofing design, surface preparation, and joint treatment.",
    },
    {
        "standard_number": "IS 101 (Part 1/Sec 1) : 1986",
        "title": "Methods of Sampling and Test for Paints, Varnishes and Related Products — Part 1: Tests on Liquid Paints (General and Physical)",
        "edition": "Third Revision",
        "document_type": "standard",
        "domain": "chemicals_materials",
        "category": "paints_coatings",
        "product_type": "paints_test_methods",
        "pub_date": "1986-04-01",
        "valid_from": "1986-04-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is101_1_1_1986",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is101_1_1_1986.pdf",
        "authority": "Bureau of Indian Standards (CHD 20)",
        "content_summary": "Standard test procedures for sampling, density determination, consistency, drying time, and flash point of liquid paints.",
    },
    {
        "standard_number": "IS 5410 : 2013",
        "title": "Cement Paint — Specification (Second Revision)",
        "edition": "Second Revision",
        "document_type": "standard",
        "domain": "chemicals_materials",
        "category": "paints_coatings",
        "product_type": "cement_paints",
        "pub_date": "2013-03-01",
        "valid_from": "2013-03-01",
        "valid_until": None,
        "source_url": "https://standardsbis.bsbedge.com/is5410_2013",
        "pdf_url": "https://standardsbis.bsbedge.com/pdf/is5410_2013.pdf",
        "authority": "Bureau of Indian Standards (CHD 20)",
        "content_summary": "Portland cement base paint for exterior masonry, Portland cement content ≥ 60% by mass, water repellency, and resistance to efflorescence.",
    },
]


class BISStandardsAdapter(BaseSourceAdapter):
    """
    Adapter for discovering and fetching BIS standards across controlled product domains.
    """

    name: str = "bis_standards"

    def __init__(self):
        self.validator = get_taxonomy_validator()
        self.valid_domains = set(self.validator.get_valid_domains())

    def _map_taxonomy_domain(self, domain_raw: Optional[str]) -> str:
        """Strictly maps domain to 7 controlled domains or 'unknown'."""
        if not domain_raw:
            return "unknown"
        dom_clean = str(domain_raw).strip().lower()
        return dom_clean if dom_clean in self.valid_domains else "unknown"

    def discover(
        self,
        domain: Optional[str] = None,
        limit: Optional[int] = None,
    ) -> List[DiscoveredStandard]:
        """
        Discovers official standards matching domain and limit filters.
        """
        target_domain = domain.strip().lower() if domain else None
        results: List[DiscoveredStandard] = []

        for record in BIS_STANDARDS_CATALOG:
            mapped_domain = self._map_taxonomy_domain(record.get("domain"))
            if target_domain and mapped_domain != target_domain:
                continue

            try:
                item = DiscoveredStandard(
                    standard_number=record["standard_number"],
                    title=record["title"],
                    edition=record.get("edition"),
                    document_type=DiscoveryDocumentType.STANDARD,
                    domain=mapped_domain,
                    category=record.get("category"),
                    product_type=record.get("product_type"),
                    source_url=record["source_url"],
                    pdf_url=record.get("pdf_url"),
                    authority=record.get("authority", "Bureau of Indian Standards"),
                    pub_date=record.get("pub_date"),
                    valid_from=record.get("valid_from"),
                    valid_until=record.get("valid_until"),
                    content_summary=record.get("content_summary"),
                )
                results.append(item)
            except Exception as e:
                logger.warning("Skipping invalid catalog record %s: %s", record.get("standard_number"), e)

            if limit and len(results) >= limit:
                break

        return results

    def fetch_metadata(self, standard_number: str) -> Optional[DiscoveredStandard]:
        """
        Looks up a specific standard code in the BIS catalog.
        """
        norm_code = normalize_standard_number(standard_number).lower().replace(" ", "")
        for record in BIS_STANDARDS_CATALOG:
            rec_code = normalize_standard_number(record["standard_number"]).lower().replace(" ", "")
            if norm_code in rec_code or rec_code in norm_code:
                mapped_domain = self._map_taxonomy_domain(record.get("domain"))
                return DiscoveredStandard(
                    standard_number=record["standard_number"],
                    title=record["title"],
                    edition=record.get("edition"),
                    document_type=DiscoveryDocumentType.STANDARD,
                    domain=mapped_domain,
                    category=record.get("category"),
                    product_type=record.get("product_type"),
                    source_url=record["source_url"],
                    pdf_url=record.get("pdf_url"),
                    authority=record.get("authority", "Bureau of Indian Standards"),
                    pub_date=record.get("pub_date"),
                    valid_from=record.get("valid_from"),
                    valid_until=record.get("valid_until"),
                    content_summary=record.get("content_summary"),
                )
        return None
