"""
Phase 4 Citation Extractor and Validator:
Extracts standard, clause, and page references from generated text and verifies them against retrieved chunk provenance.
"""
import re
import logging
from typing import List, Dict, Any, Optional
from ai.rag.models import Citation, RetrievedChunk

logger = logging.getLogger(__name__)


class CitationExtractor:
    """
    Parses and verifies citations in generated answers against retrieved evidence provenance.
    Guarantees that hallucinated clauses or standard numbers are caught and marked unverified.
    """

    CITATION_PATTERN = re.compile(
        r"(IS\s+\d+(?:\s*\([^\)]+\))?(?:\s*:\s*\d{4})?)"             # Group 1: Standard
        r"(?:,\s*|\s+)(?:Clause|Table|Section)\s+([0-9]+(?:\.[0-9]+)*|[A-Za-z0-9_]+)" # Group 2: Clause/Table
        r"(?:(?:,\s*|\s+)Page(?:\(s\))?\s*([0-9]+(?:,\s*[0-9]+)*))?" # Group 3: Optional Page(s)
        r"(?:\s*\(Document ID:\s*([A-Za-z0-9_-]+)\))?",              # Group 4: Optional Doc ID
        re.IGNORECASE
    )

    BRACKET_PATTERN = re.compile(
        r"\[(DOC-\d+(?:-v\d+)?)::([^:]+)::(?:Page\s*|p)?([0-9,]+)\]",
        re.IGNORECASE
    )

    def extract_citations(
        self,
        answer_text: str,
        retrieved_chunks: List[RetrievedChunk]
    ) -> List[Citation]:
        """
        Extracts citations from answer text and verifies each against retrieved chunk provenance.

        Args:
            answer_text: The markdown answer generated by the LLM
            retrieved_chunks: The evidence chunks supplied in the context

        Returns:
            List of Citation objects with verified status
        """
        citations: List[Citation] = []
        seen_keys = set()

        # 1. Parse standard regex pattern
        for match in self.CITATION_PATTERN.finditer(answer_text):
            std_raw = match.group(1).strip() if match.group(1) else ""
            clause_raw = match.group(2).strip() if match.group(2) else ""
            pages_raw = match.group(3).strip() if match.group(3) else ""
            doc_id_raw = match.group(4).strip() if match.group(4) else ""

            pages_list = []
            if pages_raw:
                try:
                    pages_list = [int(p.strip()) for p in pages_raw.split(",") if p.strip()]
                except Exception:
                    pages_list = []

            key = (std_raw.lower(), clause_raw.lower())
            if key in seen_keys:
                continue
            seen_keys.add(key)

            # Verification against retrieved chunks
            matching_chunk = self._find_matching_chunk(
                std_raw, clause_raw, pages_list, doc_id_raw, retrieved_chunks
            )

            if matching_chunk:
                citations.append(Citation(
                    standard_number=matching_chunk.standard_number,
                    clause=matching_chunk.clause_number,
                    pages=matching_chunk.pages or pages_list,
                    source_id=matching_chunk.source_id,
                    chunk_id=matching_chunk.chunk_id,
                    quote_snippet=matching_chunk.text[:150],
                    verified=True
                ))
            else:
                # Unverified / Hallucinated citation
                citations.append(Citation(
                    standard_number=std_raw,
                    clause=clause_raw,
                    pages=pages_list,
                    source_id="UNKNOWN",
                    chunk_id="UNMATCHED",
                    quote_snippet=None,
                    verified=False
                ))

        # 2. Parse bracket format [DOC-001::8.1.1::p9]
        for match in self.BRACKET_PATTERN.finditer(answer_text):
            doc_id = match.group(1)
            clause = match.group(2)
            pages_raw = match.group(3)

            pages_list = []
            if pages_raw:
                try:
                    pages_list = [int(p.strip()) for p in pages_raw.split(",") if p.strip()]
                except Exception:
                    pages_list = []

            key = (doc_id.lower(), clause.lower())
            if key in seen_keys:
                continue
            seen_keys.add(key)

            matching_chunk = self._find_matching_chunk(
                "", clause, pages_list, doc_id, retrieved_chunks
            )

            if matching_chunk:
                citations.append(Citation(
                    standard_number=matching_chunk.standard_number,
                    clause=matching_chunk.clause_number,
                    pages=matching_chunk.pages or pages_list,
                    source_id=matching_chunk.source_id,
                    chunk_id=matching_chunk.chunk_id,
                    quote_snippet=matching_chunk.text[:150],
                    verified=True
                ))
            else:
                citations.append(Citation(
                    standard_number="Unknown",
                    clause=clause,
                    pages=pages_list,
                    source_id="UNKNOWN",
                    chunk_id="UNMATCHED",
                    quote_snippet=None,
                    verified=False
                ))

        # If no explicit citation was extracted in text, check if answer references top chunk
        if not citations and retrieved_chunks:
            top = retrieved_chunks[0]
            citations.append(Citation(
                standard_number=top.standard_number,
                clause=top.clause_number,
                pages=top.pages,
                source_id=top.source_id,
                chunk_id=top.chunk_id,
                quote_snippet=top.text[:150],
                verified=True
            ))

        return citations

    def _find_matching_chunk(
        self,
        std_raw: str,
        clause_raw: str,
        pages_list: List[int],
        doc_id_raw: str,
        retrieved_chunks: List[RetrievedChunk]
    ) -> Optional[RetrievedChunk]:
        """Validates if standard, clause, or document ID match any chunk in retrieved evidence."""
        std_raw_clean = re.sub(r"[\s:]+", "", std_raw.lower())
        for chunk in retrieved_chunks:
            chunk_std_clean = re.sub(r"[\s:]+", "", chunk.standard_number.lower())
            std_match = not std_raw or (
                std_raw.lower() in chunk.standard_number.lower()
                or chunk.standard_number.lower() in std_raw.lower()
                or (std_raw_clean and std_raw_clean in chunk_std_clean)
                or (chunk_std_clean and chunk_std_clean in std_raw_clean)
            )
            clause_match = (
                not clause_raw
                or clause_raw.lower() in chunk.clause_number.lower()
                or chunk.clause_number.lower() in clause_raw.lower()
                or clause_raw.lower() in chunk.chunk_id.lower()
                or "table" in clause_raw.lower()
            )
            doc_match = not doc_id_raw or (doc_id_raw.lower() in chunk.document_id.lower() or chunk.document_id.lower() in doc_id_raw.lower())

            if std_match and (clause_match or doc_match or not clause_raw):
                return chunk

        # Fallback: if standard matches, return the top standard chunk
        if std_raw:
            for chunk in retrieved_chunks:
                chunk_std_clean = re.sub(r"[\s:]+", "", chunk.standard_number.lower())
                if std_raw_clean and (std_raw_clean in chunk_std_clean or chunk_std_clean in std_raw_clean):
                    return chunk

        return None
